import "dotenv/config";
import { hash } from "@node-rs/argon2";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

const users = [
  {
    username: "admin",
    email: "admin@admin.com",
    firstName: "Admin",
    lastName: "Admin",
  },
  {
    username: "user",
    email: process.env.EMAIL!,
    firstName: "User",
    lastName: "User",
  },
];

const tickets = [
  {
    title: "Ticket 1",
    content: "This is the first ticket from the database",
    status: "DONE" as const,
    deadline: new Date().toISOString().split("T")[0],
    bounty: 499,
  },
  {
    title: "Ticket 2",
    content: "This is the second ticket from the database",
    status: "OPEN" as const,
    deadline: new Date().toISOString().split("T")[0],
    bounty: 399,
  },
  {
    title: "Ticket 3",
    content: "This is the third ticket from the database",
    status: "IN_PROGRESS" as const,
    deadline: new Date().toISOString().split("T")[0],
    bounty: 599,
  },
];

const seed = async () => {
  const t0 = performance.now();
  console.log("Seeding database...");

  // we must delete the ticket first before the user because of the foreign key in tickets that that references the user
  await prisma.user.deleteMany();
  await prisma.ticket.deleteMany();

  // when a user logs in using their email, we need to take the plain password and then compare it to the hashed one in the db
  // more performant to hash the password once here instead of polluting the user array with non static variables
  const passwordHash = await hash("geheimnis");

  // we create user objects using the map function so we can add the hashed password to the users array
  // createManyAndReturn returns the object created in the db
  const dbUsers = await prisma.user.createManyAndReturn({
    data: users.map((user) => ({
      ...user,
      passwordHash,
    })),
  });

  // to get our userId for the ticket we loop through the tickets and add the userId to each ticket
  // it will always take the first users id (which in this case is admin)
  // remember: our user model in our prisma schema has an id generated by the database so we need to get it from the dbUsers object
  await prisma.ticket.createMany({
    data: tickets.map((ticket) => ({
      ...ticket,
      userId: dbUsers[0].id,
    })),
  });

  const t1 = performance.now();
  console.log(`Database seeded in ${(t1 - t0).toFixed(2)} milliseconds.`);
};

seed();
